/**
 * Iconography Governance System
 * Econ-IQ enforces Lucide React as the exclusive icon pack.
 */

import {
  LayoutDashboard,
  Users,
  BarChart3,
  User as UserIcon,
  Key,
  Settings,
  LogOut,
  ChevronUp,
  ChevronsUpDown,
  Plus,
  Trash2,
  Lock,
  Mail,
  Building,
  CheckCircle,
  AlertTriangle,
  XCircle,
  Eye,
  EyeOff,
  Search,
  Filter,
  Download,
  Upload,
  UserPlus,
  UserMinus,
  Ban,
  ArrowUpDown,
  TrendingUp,
  TrendingDown,
  Info,
  ExternalLink,
  Shield,
  HelpCircle,
} from 'lucide-react';

export const icons = {
  Dashboard: LayoutDashboard,
  Users: Users,
  Reports: BarChart3,
  Profile: UserIcon,
  Key: Key,
  Settings: Settings,
  LogOut: LogOut,
  ChevronUp: ChevronUp,
  ChevronsUpDown: ChevronsUpDown,
  Plus: Plus,
  Delete: Trash2,
  Lock: Lock,
  Mail: Mail,
  Organization: Building,
  Success: CheckCircle,
  Warning: AlertTriangle,
  Error: XCircle,
  Show: Eye,
  Hide: EyeOff,
  Search: Search,
  Filter: Filter,
  Download: Download,
  Upload: Upload,
  AddUser: UserPlus,
  RemoveUser: UserMinus,
  Revoke: Ban,
  Sort: ArrowUpDown,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  Info: Info,
  External: ExternalLink,
  Shield: Shield,
  Help: HelpCircle,
} as const;

export type IconName = keyof typeof icons;

export function getIcon(name: IconName) {
  return icons[name];
}
export {
  LayoutDashboard,
  Users,
  BarChart3,
  UserIcon,
  Key,
  Settings,
  LogOut,
  ChevronUp,
  ChevronsUpDown,
  Plus,
  Trash2,
  Lock,
  Mail,
  Building,
  CheckCircle,
  AlertTriangle,
  XCircle,
  Eye,
  EyeOff,
  Search,
  Filter,
  Download,
  Upload,
  UserPlus,
  UserMinus,
  Ban,
  ArrowUpDown,
  TrendingUp,
  TrendingDown,
  Info,
  ExternalLink,
  Shield,
  HelpCircle,
};
export type { LucideIcon } from 'lucide-react';
